#!/usr/bin/env bash

device=$(cat /proc/net/wireless | perl -ne '/(\w+):/ && print $1')
status=$(cat /sys/class/net/${device}/operstate)

URGENT_VALUE=20

if [[ "${status}" == "up" ]]; then
  if [[ -d "/sys/class/net/${device}/wireless" ]]; then
    quality=$(grep ${device} /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
    echo "${quality}%"
    echo "${quality}%"
    echo "#ffffff"

    if [[ "${quality}" -le "${URGENT_VALUE}" ]]; then
      exit 33
    fi
  else
    echo "on"
    echo "on"
    echo ""
  fi
fi

